# Generated by Django 3.0.4 on 2020-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200509_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
